### ISSUE TITLE
TypeError: Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by JugnuPathak** [hootlex/vuejs-paginator#33] opened 2017-12-12 13:30 UTC
Im getting error 

```
[Vue warn]: Error in created hook: "TypeError: Cannot read property 'get' of undefined"

found in

---> <VPaginator>
       <Root>
```

https://jsfiddle.net/JunedLanja/oty8w8go/1/

**Comment by hootlex** [comment] 2017-12-12 13:51
Thanks for the repro link!

This happens because `Vue.prototype.$http` is null. You have to either use Vue Resource or set `Vue.prototype.$http = axios` if you are using axios.

Duplicate of https://github.com/hootlex/vuejs-paginator/issues/24

**Closed by hootlex** 2017-12-12 13:51 UTC
